### ISSUE TITLE
Help with Basic Command

### ISSUE THREAD

**Issue by jasondaming** [LORD-MicroStrain/Protocols#1]
I am trying to communicate from a CompactRIO to a Serial BaseStation and in turn to a node.  I have tried to assemble a basic ping command but got no response when I tried it.  The command I sent in hex was:

AC04 0013 0900 0200 027F 7FF4 90F2 22

Do you have an example of a command I could send that should definitely get a response so I know that all of my hardware is setup correctly.  Did I construct the command above correctly or did I miss something?  I am not sure I did the checksum properly.

**Comment by rwslord** [comment]
It looks like you are trying to send the ASPP3 command. This command is only supported by our very recent generation of products ([G-Link-200](http://www.microstrain.com/wireless/G-Link-200-8G), [V-Link-200](http://www.microstrain.com/wireless/V-LINK-200), and the [WSDA-200-USB BaseStation](http://www.microstrain.com/wireless/WSDA-200-USB)).

Since you are mentioning a _Serial_ BaseStation, I'm thinking you don't have the WSDA-200-USB. Therefore, can you try the [Ping ASPP1](https://github.com/LORD-MicroStrain/Protocols/blob/master/Wireless/Commands.md#ping-v1) command?

**Comment by jasondaming** [comment]
I am now able to get some response so that is better.  When I send 01 I get back 01.

I tried doing the Ping ASPP1 command (AA05 0001 3902 0002 0142) but I got back 21?

So then I tried pinging the base station ([V2](https://github.com/LORD-MicroStrain/Protocols/blob/master/Wireless/Commands.md#ping-base-station-v2)) which I was hoping was simpler with AA0E 3012 3402 0001 1275 and still got back 21.

I assume 21 is some sort of error message?  I have confirmed that this HW works in Sensor Connect.

**Comment by rwslord** [comment]
Is the Node Address of your Wireless Node 313 (0x0139)? Assuming that it is, your checksum is incorrect, which is likely causing the problem. It should be 0x0043 instead of 0x0142.
`0x05 + 0x00 + 0x01 + 0x39 + 0x02 + 0x00 + 0x02 = 0x0043`

As far as the BaseStation command you are trying to use, it may be a similar case of that command not being supported by your hardware. Can you tell me what the firmware version of your BaseStation is (from SensorConnect)?

Also, could I ask what you are trying to ultimately achieve? I'm curious if you've looked in to [MSCL](https://github.com/LORD-MicroStrain/MSCL), as getting that up and running would save you from having to worry about how the actual protocol works at a low level. Feel free to PM me at richard_stoneback@lord.com if you prefer to chat about your project offline.

**Comment by rwslord** [comment]
Oh, and 0x21 is indicating that the command failed.

**Comment by jasondaming** [comment]
That was my whole problem that I had the node number written out rather than the node number converted to hex.  139 was the node number which when I used 8B instead everything started working
